### ISSUE TITLE
Good day. - setup instructions

### ISSUE THREAD

**Issue by Artapel** [botorabi/TeamSpeakPHPBots#2]
Can you perhaps provide me with setup instructions, i cannot seem to determine how to get the bot running and the interface to display.

I am using CentOS with apache, php and mysql

**Comment by botorabi** [comment]
Hi,

for instructions to setup and run an example basing on the framework, please visit this page:

  https://github.com/botorabi/TeamSpeakPHPBots/tree/master/examples/MultipleBotTypes

In principle you have to configure the bot server, a database access, and setup a web server for accessing the bot configuration. While the bot server is running, any changes to bot configuration via web access will be reflected immediately on the bot server.

Please follow the instructions mentioned in the URL above and let me know if you run into any problem.

Cheers
boto

**Comment by botorabi** [comment]
I am going to close this issue. If you need further assistance then feel free to reopen it.

Cheers
boto
