### ISSUE TITLE
Admin pass

### ISSUE THREAD

**Issue by php-web-systems-constructions** [botorabi/TeamSpeakPHPBots#3]
Hi,

i've just downloaded this resource, it looks nice. I've opened example. But i need some admin login informations, i don't know this informations. I alredy filled the configuration, but I don't know this informattion - email or name and password.

**Comment by botorabi** [comment]
Hi,

the initial user credentials are created in file:

   TeamSpeakPHPBots/libraries/TeamSpeakPHPBots/setup/create-database.sql

User name and password are both 'admin'. Don't forget to change them immediately after the setup.

Cheers
boto

**Comment by php-web-systems-constructions** [comment]
Ah, well, thank you. And I have one more question. Is it possible to run a SQL file through a browser? When I open the address, the file will be downloaded. I'm interested in it longer, I take the chance to get the answer :D

**Comment by botorabi** [comment]
If you use MySQL then you may take a look on **MySQL Workbench** or **phpMyAdmin**

**Comment by php-web-systems-constructions** [comment]
I'm probably stupid or what ... When I click on any link in the admin panel, it opens a 404 error and redirects back to the administration.

But it does not matter because the web server does not run a shell script - it does not allow my hosting :(
